# Generated by Django 4.1.6 on 2023-02-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "user"), ("admin", "admin")],
                default="user",
                max_length=9,
                verbose_name="Пользовательская роль",
            ),
        ),
    ]
